# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/PCCarloDev/rpi/CRpi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/PCCarloDev/rpi/CRpi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/PCCarloDev/rpi/CRpi/CMakeFiles /media/PCCarloDev/rpi/CRpi/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/PCCarloDev/rpi/CRpi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CRpi

# Build rule for target.
CRpi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CRpi
.PHONY : CRpi

# fast build rule for target.
CRpi/fast:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/build
.PHONY : CRpi/fast

#=============================================================================
# Target rules for targets named demo

# Build rule for target.
demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 demo
.PHONY : demo

# fast build rule for target.
demo/fast:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/build
.PHONY : demo/fast

src/demo/demo.o: src/demo/demo.cpp.o
.PHONY : src/demo/demo.o

# target to build an object file
src/demo/demo.cpp.o:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/src/demo/demo.cpp.o
.PHONY : src/demo/demo.cpp.o

src/demo/demo.i: src/demo/demo.cpp.i
.PHONY : src/demo/demo.i

# target to preprocess a source file
src/demo/demo.cpp.i:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/src/demo/demo.cpp.i
.PHONY : src/demo/demo.cpp.i

src/demo/demo.s: src/demo/demo.cpp.s
.PHONY : src/demo/demo.s

# target to generate assembly for a file
src/demo/demo.cpp.s:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/src/demo/demo.cpp.s
.PHONY : src/demo/demo.cpp.s

src/lib/memoryManagement/addressing.o: src/lib/memoryManagement/addressing.cpp.o
.PHONY : src/lib/memoryManagement/addressing.o

# target to build an object file
src/lib/memoryManagement/addressing.cpp.o:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/memoryManagement/addressing.cpp.o
.PHONY : src/lib/memoryManagement/addressing.cpp.o

src/lib/memoryManagement/addressing.i: src/lib/memoryManagement/addressing.cpp.i
.PHONY : src/lib/memoryManagement/addressing.i

# target to preprocess a source file
src/lib/memoryManagement/addressing.cpp.i:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/memoryManagement/addressing.cpp.i
.PHONY : src/lib/memoryManagement/addressing.cpp.i

src/lib/memoryManagement/addressing.s: src/lib/memoryManagement/addressing.cpp.s
.PHONY : src/lib/memoryManagement/addressing.s

# target to generate assembly for a file
src/lib/memoryManagement/addressing.cpp.s:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/memoryManagement/addressing.cpp.s
.PHONY : src/lib/memoryManagement/addressing.cpp.s

src/lib/memoryManagement/cacheCoherentMemoryProvider.o: src/lib/memoryManagement/cacheCoherentMemoryProvider.cpp.o
.PHONY : src/lib/memoryManagement/cacheCoherentMemoryProvider.o

# target to build an object file
src/lib/memoryManagement/cacheCoherentMemoryProvider.cpp.o:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/memoryManagement/cacheCoherentMemoryProvider.cpp.o
.PHONY : src/lib/memoryManagement/cacheCoherentMemoryProvider.cpp.o

src/lib/memoryManagement/cacheCoherentMemoryProvider.i: src/lib/memoryManagement/cacheCoherentMemoryProvider.cpp.i
.PHONY : src/lib/memoryManagement/cacheCoherentMemoryProvider.i

# target to preprocess a source file
src/lib/memoryManagement/cacheCoherentMemoryProvider.cpp.i:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/memoryManagement/cacheCoherentMemoryProvider.cpp.i
.PHONY : src/lib/memoryManagement/cacheCoherentMemoryProvider.cpp.i

src/lib/memoryManagement/cacheCoherentMemoryProvider.s: src/lib/memoryManagement/cacheCoherentMemoryProvider.cpp.s
.PHONY : src/lib/memoryManagement/cacheCoherentMemoryProvider.s

# target to generate assembly for a file
src/lib/memoryManagement/cacheCoherentMemoryProvider.cpp.s:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/memoryManagement/cacheCoherentMemoryProvider.cpp.s
.PHONY : src/lib/memoryManagement/cacheCoherentMemoryProvider.cpp.s

src/lib/memoryManagement/physMemoryManagement.o: src/lib/memoryManagement/physMemoryManagement.cpp.o
.PHONY : src/lib/memoryManagement/physMemoryManagement.o

# target to build an object file
src/lib/memoryManagement/physMemoryManagement.cpp.o:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/memoryManagement/physMemoryManagement.cpp.o
.PHONY : src/lib/memoryManagement/physMemoryManagement.cpp.o

src/lib/memoryManagement/physMemoryManagement.i: src/lib/memoryManagement/physMemoryManagement.cpp.i
.PHONY : src/lib/memoryManagement/physMemoryManagement.i

# target to preprocess a source file
src/lib/memoryManagement/physMemoryManagement.cpp.i:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/memoryManagement/physMemoryManagement.cpp.i
.PHONY : src/lib/memoryManagement/physMemoryManagement.cpp.i

src/lib/memoryManagement/physMemoryManagement.s: src/lib/memoryManagement/physMemoryManagement.cpp.s
.PHONY : src/lib/memoryManagement/physMemoryManagement.s

# target to generate assembly for a file
src/lib/memoryManagement/physMemoryManagement.cpp.s:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/memoryManagement/physMemoryManagement.cpp.s
.PHONY : src/lib/memoryManagement/physMemoryManagement.cpp.s

src/lib/notMine/mailbox.o: src/lib/notMine/mailbox.cpp.o
.PHONY : src/lib/notMine/mailbox.o

# target to build an object file
src/lib/notMine/mailbox.cpp.o:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/notMine/mailbox.cpp.o
.PHONY : src/lib/notMine/mailbox.cpp.o

src/lib/notMine/mailbox.i: src/lib/notMine/mailbox.cpp.i
.PHONY : src/lib/notMine/mailbox.i

# target to preprocess a source file
src/lib/notMine/mailbox.cpp.i:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/notMine/mailbox.cpp.i
.PHONY : src/lib/notMine/mailbox.cpp.i

src/lib/notMine/mailbox.s: src/lib/notMine/mailbox.cpp.s
.PHONY : src/lib/notMine/mailbox.s

# target to generate assembly for a file
src/lib/notMine/mailbox.cpp.s:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/notMine/mailbox.cpp.s
.PHONY : src/lib/notMine/mailbox.cpp.s

src/lib/peripherals/clockManager.o: src/lib/peripherals/clockManager.cpp.o
.PHONY : src/lib/peripherals/clockManager.o

# target to build an object file
src/lib/peripherals/clockManager.cpp.o:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/peripherals/clockManager.cpp.o
.PHONY : src/lib/peripherals/clockManager.cpp.o

src/lib/peripherals/clockManager.i: src/lib/peripherals/clockManager.cpp.i
.PHONY : src/lib/peripherals/clockManager.i

# target to preprocess a source file
src/lib/peripherals/clockManager.cpp.i:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/peripherals/clockManager.cpp.i
.PHONY : src/lib/peripherals/clockManager.cpp.i

src/lib/peripherals/clockManager.s: src/lib/peripherals/clockManager.cpp.s
.PHONY : src/lib/peripherals/clockManager.s

# target to generate assembly for a file
src/lib/peripherals/clockManager.cpp.s:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/peripherals/clockManager.cpp.s
.PHONY : src/lib/peripherals/clockManager.cpp.s

src/lib/peripherals/dma.o: src/lib/peripherals/dma.cpp.o
.PHONY : src/lib/peripherals/dma.o

# target to build an object file
src/lib/peripherals/dma.cpp.o:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/peripherals/dma.cpp.o
.PHONY : src/lib/peripherals/dma.cpp.o

src/lib/peripherals/dma.i: src/lib/peripherals/dma.cpp.i
.PHONY : src/lib/peripherals/dma.i

# target to preprocess a source file
src/lib/peripherals/dma.cpp.i:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/peripherals/dma.cpp.i
.PHONY : src/lib/peripherals/dma.cpp.i

src/lib/peripherals/dma.s: src/lib/peripherals/dma.cpp.s
.PHONY : src/lib/peripherals/dma.s

# target to generate assembly for a file
src/lib/peripherals/dma.cpp.s:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/peripherals/dma.cpp.s
.PHONY : src/lib/peripherals/dma.cpp.s

src/lib/peripherals/gpio.o: src/lib/peripherals/gpio.cpp.o
.PHONY : src/lib/peripherals/gpio.o

# target to build an object file
src/lib/peripherals/gpio.cpp.o:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/peripherals/gpio.cpp.o
.PHONY : src/lib/peripherals/gpio.cpp.o

src/lib/peripherals/gpio.i: src/lib/peripherals/gpio.cpp.i
.PHONY : src/lib/peripherals/gpio.i

# target to preprocess a source file
src/lib/peripherals/gpio.cpp.i:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/peripherals/gpio.cpp.i
.PHONY : src/lib/peripherals/gpio.cpp.i

src/lib/peripherals/gpio.s: src/lib/peripherals/gpio.cpp.s
.PHONY : src/lib/peripherals/gpio.s

# target to generate assembly for a file
src/lib/peripherals/gpio.cpp.s:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/peripherals/gpio.cpp.s
.PHONY : src/lib/peripherals/gpio.cpp.s

src/lib/peripherals/pwm.o: src/lib/peripherals/pwm.cpp.o
.PHONY : src/lib/peripherals/pwm.o

# target to build an object file
src/lib/peripherals/pwm.cpp.o:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/peripherals/pwm.cpp.o
.PHONY : src/lib/peripherals/pwm.cpp.o

src/lib/peripherals/pwm.i: src/lib/peripherals/pwm.cpp.i
.PHONY : src/lib/peripherals/pwm.i

# target to preprocess a source file
src/lib/peripherals/pwm.cpp.i:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/peripherals/pwm.cpp.i
.PHONY : src/lib/peripherals/pwm.cpp.i

src/lib/peripherals/pwm.s: src/lib/peripherals/pwm.cpp.s
.PHONY : src/lib/peripherals/pwm.s

# target to generate assembly for a file
src/lib/peripherals/pwm.cpp.s:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/peripherals/pwm.cpp.s
.PHONY : src/lib/peripherals/pwm.cpp.s

src/lib/utils/pwmByDma.o: src/lib/utils/pwmByDma.cpp.o
.PHONY : src/lib/utils/pwmByDma.o

# target to build an object file
src/lib/utils/pwmByDma.cpp.o:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/utils/pwmByDma.cpp.o
.PHONY : src/lib/utils/pwmByDma.cpp.o

src/lib/utils/pwmByDma.i: src/lib/utils/pwmByDma.cpp.i
.PHONY : src/lib/utils/pwmByDma.i

# target to preprocess a source file
src/lib/utils/pwmByDma.cpp.i:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/utils/pwmByDma.cpp.i
.PHONY : src/lib/utils/pwmByDma.cpp.i

src/lib/utils/pwmByDma.s: src/lib/utils/pwmByDma.cpp.s
.PHONY : src/lib/utils/pwmByDma.s

# target to generate assembly for a file
src/lib/utils/pwmByDma.cpp.s:
	$(MAKE) -f CMakeFiles/CRpi.dir/build.make CMakeFiles/CRpi.dir/src/lib/utils/pwmByDma.cpp.s
.PHONY : src/lib/utils/pwmByDma.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... CRpi"
	@echo "... demo"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/demo/demo.o"
	@echo "... src/demo/demo.i"
	@echo "... src/demo/demo.s"
	@echo "... src/lib/memoryManagement/addressing.o"
	@echo "... src/lib/memoryManagement/addressing.i"
	@echo "... src/lib/memoryManagement/addressing.s"
	@echo "... src/lib/memoryManagement/cacheCoherentMemoryProvider.o"
	@echo "... src/lib/memoryManagement/cacheCoherentMemoryProvider.i"
	@echo "... src/lib/memoryManagement/cacheCoherentMemoryProvider.s"
	@echo "... src/lib/memoryManagement/physMemoryManagement.o"
	@echo "... src/lib/memoryManagement/physMemoryManagement.i"
	@echo "... src/lib/memoryManagement/physMemoryManagement.s"
	@echo "... src/lib/notMine/mailbox.o"
	@echo "... src/lib/notMine/mailbox.i"
	@echo "... src/lib/notMine/mailbox.s"
	@echo "... src/lib/peripherals/clockManager.o"
	@echo "... src/lib/peripherals/clockManager.i"
	@echo "... src/lib/peripherals/clockManager.s"
	@echo "... src/lib/peripherals/dma.o"
	@echo "... src/lib/peripherals/dma.i"
	@echo "... src/lib/peripherals/dma.s"
	@echo "... src/lib/peripherals/gpio.o"
	@echo "... src/lib/peripherals/gpio.i"
	@echo "... src/lib/peripherals/gpio.s"
	@echo "... src/lib/peripherals/pwm.o"
	@echo "... src/lib/peripherals/pwm.i"
	@echo "... src/lib/peripherals/pwm.s"
	@echo "... src/lib/utils/pwmByDma.o"
	@echo "... src/lib/utils/pwmByDma.i"
	@echo "... src/lib/utils/pwmByDma.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

